/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boardgame;

/**
 *
 * @author Ruairi
 */
public class helpPage extends javax.swing.JFrame {

    /**
     * Creates new form helpPage
     */
    public helpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        closeHelpButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HELP");
        setBounds(new java.awt.Rectangle(500, 0, 50, 0));
        setMaximumSize(new java.awt.Dimension(1145, 404));
        setMinimumSize(new java.awt.Dimension(1145, 404));
        setName("Help");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/How to play.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, 90));

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("On your turn:         1 Click spinner button and move around the board.\n\t      2 Follow the instructions on the space you land.\n\t      3 Your turn is over so click the 'End Turn' button.\n\t\tThe next player now takes their turn.\n\nSpecial Spins:           When you spin a '1' click the erupt button on \n\t       the volcano until it erupts and collect the\n\t       amount shown.\n\t       When you spin a 10, each player is one step closer to\n\t       retirement!\n               \t       If the life bar depletes - it's Game Over.\n\t       Move your car 10 spaces.\n\t        \nGame Over:         When the age reaches its limit the game is over."); // NOI18N
        jScrollPane1.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 510, 290));

        closeHelpButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        closeHelpButton.setText("CREDITS");
        closeHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeHelpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeHelpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 121, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/helpScreenTitleTRANS.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1143, 11, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/old_paper.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1159)/2, (screenSize.height-460)/2, 1159, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void closeHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeHelpButtonActionPerformed
        BoardGame.missionControl.MessageBoxShow("Team Liquid is made up of\n" + "Darren Murray\n" + "David Gray\n" + "Don Davies\n" + "Paddy McMahon\n" + "Ruairi\n\n" + "Software used - PLXR, PHOTOSHOP and NETBEANS\n\n" + "Credit to KNUCKLES T15 & NINTENDO for the sprites used\nhttp://www.spriteresource.com/", "Credits"); 
    }//GEN-LAST:event_closeHelpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(helpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(helpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(helpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(helpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new helpPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeHelpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
