/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boardgame;

/**
 *
 * @author Team Liquid
 */
public class islandSelectGUI extends javax.swing.JFrame {

    /**
     * Creates new form islandSelectGUI
     */
    public islandSelectGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIslandSelectHeader = new javax.swing.JLabel();
        btnTopLeft = new javax.swing.JButton();
        btnTopRight = new javax.swing.JButton();
        btnBottomLeft = new javax.swing.JButton();
        btnBottomRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIslandSelectHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIslandSelectHeader.setText("Choose an Island to travel to");

        btnTopLeft.setText("Top Left");
        btnTopLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopLeftActionPerformed(evt);
            }
        });

        btnTopRight.setText("Top Right");
        btnTopRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopRightActionPerformed(evt);
            }
        });

        btnBottomLeft.setText("Bottom Left");
        btnBottomLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBottomLeftActionPerformed(evt);
            }
        });

        btnBottomRight.setText("Bottom Right");
        btnBottomRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBottomRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIslandSelectHeader)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTopLeft)
                            .addComponent(btnBottomLeft))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBottomRight)
                            .addComponent(btnTopRight))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblIslandSelectHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTopLeft)
                    .addComponent(btnTopRight))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBottomLeft)
                    .addComponent(btnBottomRight))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTopLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopLeftActionPerformed
              
        BoardGame.missionControl.players[BoardGame.missionControl.playerTurn].changeIsland(10);
        BoardGame.missionControl.setIsland(10);
        dispose();
    }//GEN-LAST:event_btnTopLeftActionPerformed

    private void btnTopRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopRightActionPerformed
        
        BoardGame.missionControl.players[BoardGame.missionControl.playerTurn].changeIsland(4);
        BoardGame.missionControl.setIsland(4);
        BoardGame.missionControl.players[BoardGame.missionControl.playerTurn].setPlayerPosition(1);
        BoardGame.missionControl.MessageBoxShow(Integer.toString(BoardGame.missionControl.players[BoardGame.missionControl.playerTurn].getPosition()), "A Title");
        //BoardGame.missionControl.movePlayer(0);
        dispose();
    }//GEN-LAST:event_btnTopRightActionPerformed

    private void btnBottomLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBottomLeftActionPerformed
        
        BoardGame.missionControl.players[BoardGame.missionControl.playerTurn].changeIsland(8);
        BoardGame.missionControl.setIsland(8);
        BoardGame.missionControl.players[BoardGame.missionControl.playerTurn].setPlayerPosition(1);
        //BoardGame.missionControl.movePlayer(0);
        dispose();
    }//GEN-LAST:event_btnBottomLeftActionPerformed

    private void btnBottomRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBottomRightActionPerformed
        
        BoardGame.missionControl.players[BoardGame.missionControl.playerTurn].changeIsland(6);
        BoardGame.missionControl.setIsland(6);
        dispose();
    }//GEN-LAST:event_btnBottomRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(islandSelectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(islandSelectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(islandSelectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(islandSelectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new islandSelectGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBottomLeft;
    private javax.swing.JButton btnBottomRight;
    private javax.swing.JButton btnTopLeft;
    private javax.swing.JButton btnTopRight;
    private javax.swing.JLabel lblIslandSelectHeader;
    // End of variables declaration//GEN-END:variables
}
