/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package boardgame;

import javax.swing.JTextField;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author Don
 */
public class startScreen extends javax.swing.JFrame {

    //declare variables 
    public static board myBoard = new board();
    public static int numberOfPlayers = 2;
    
    /**
     * Creates new form startScreen
     */
    public startScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnNumberOfPlayers = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        chkPlayer1 = new javax.swing.JCheckBox();
        chkPlayer2 = new javax.swing.JCheckBox();
        chkPlayer3 = new javax.swing.JCheckBox();
        chkPlayer4 = new javax.swing.JCheckBox();
        chkPlayer5 = new javax.swing.JCheckBox();
        chkPlayer6 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        sldrRetirement = new javax.swing.JSlider();
        lblRetirementInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("\"Game Of Life\"");

        spnNumberOfPlayers.setModel(new javax.swing.SpinnerNumberModel(2, 2, 6, 1));
        spnNumberOfPlayers.setMaximumSize(new java.awt.Dimension(0, 0));
        spnNumberOfPlayers.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onChangeNumber2(evt);
            }
        });
        spnNumberOfPlayers.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                onChangeNumber1(evt);
            }
        });

        jLabel3.setText("Players");

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Start Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Do you want to go to college?");

        sldrRetirement.setMajorTickSpacing(10);
        sldrRetirement.setMinimum(10);
        sldrRetirement.setMinorTickSpacing(10);
        sldrRetirement.setSnapToTicks(true);
        sldrRetirement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                printLabel(evt);
            }
        });

        lblRetirementInfo.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnNumberOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkPlayer2)
                                    .addComponent(chkPlayer1)
                                    .addComponent(chkPlayer3)
                                    .addComponent(chkPlayer4)
                                    .addComponent(chkPlayer5)
                                    .addComponent(chkPlayer6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(sldrRetirement, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lblRetirementInfo)))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnNumberOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPlayer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPlayer2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPlayer3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkPlayer4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkPlayer5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPlayer6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblRetirementInfo)
                        .addComponent(sldrRetirement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * runs a few bits and pieces when the button at the bottom of the form is
     * clicked.
     *
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                
                
                JLabel labels[] = {myBoard.getjLabel1(),myBoard.getjLabel2(),myBoard.getjLabel3(),myBoard.getjLabel4(),myBoard.getjLabel5(),myBoard.getjLabel6()};
                JTextField textFields[] = {jTextField1,jTextField2,jTextField3,jTextField4,jTextField5,jTextField6};
                JCheckBox collegeCheck[] = {chkPlayer1,chkPlayer2,chkPlayer3,chkPlayer4,chkPlayer5,chkPlayer6};
                
                //sets the names on the board 
                if (!(jTextField1.getText().equals("")) && !(jTextField2.getText().equals("")))
                {
                    int spinnerValue = (int) spnNumberOfPlayers.getValue();
                    for(int i=0; i<spinnerValue;i++){
                        labels[i].setText(textFields[i].getText());
                    }
                    
                    numberOfPlayers = ((int) spnNumberOfPlayers.getValue()-1);
                    BoardGame.missionControl.setUp();
                    myBoard.setVisible(true);
                    
                    BoardGame.missionControl.setLifespan(sldrRetirement.getValue());
                    
                    
                    //BoardGame.missionControl.MessageBoxShow(Integer.toString(BoardGame.missionControl.getLifespan()), "Validation Error");
                //  disposes the current form - in this case it is the
                //  start form when the user selects players and such.
                    dispose();
                }
                //validation if textbox is empty
                else
                {
                    BoardGame.missionControl.MessageBoxShow("AHHHHHHH!!!!", "Validation Error");
                    
                    System.out.println("NO");
                }
               
                //set players to college or not 
                
                for(int i=0;i<collegeCheck.length;i++){
                    
                    if(collegeCheck[i].isSelected())
                    BoardGame.missionControl.players[i].changeIsland(2);
                }
                
                
                
                
                
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void onChangeNumber2(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onChangeNumber2
        int numberOfPlayers = (int) spnNumberOfPlayers.getValue();
        
        //System.out.println("number of players =" + numberOfPlayers);
        
        if (numberOfPlayers == 2)
        {
            jTextField6.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField3.setEnabled(false);
        }
        
        if (numberOfPlayers == 3)
        {
            jTextField6.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField3.setEnabled(true);
        }
        
        if (numberOfPlayers == 4)
        {
            jTextField6.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField4.setEnabled(true);
            jTextField3.setEnabled(true);
        }
        
        if (numberOfPlayers == 5)
        {
            jTextField6.setEnabled(false);
            jTextField5.setEnabled(true);
            jTextField4.setEnabled(true);
            jTextField3.setEnabled(true);
        }
        
        if (numberOfPlayers == 6)
        {
            jTextField6.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField4.setEnabled(true);
            jTextField3.setEnabled(true);
        }
    }//GEN-LAST:event_onChangeNumber2

    private void onChangeNumber1(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_onChangeNumber1
        int numberOfPlayers = (int) spnNumberOfPlayers.getValue();
        
        //System.out.println("number of players =" + numberOfPlayers);
        
        if (numberOfPlayers == 2)
        {
            jTextField6.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField3.setEnabled(false);
        }
        
        if (numberOfPlayers == 3)
        {
            jTextField6.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField3.setEnabled(true);
        }
        
        if (numberOfPlayers == 4)
        {
            jTextField6.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField4.setEnabled(true);
            jTextField3.setEnabled(true);
        }
        
        if (numberOfPlayers == 5)
        {
            jTextField6.setEnabled(false);
            jTextField5.setEnabled(true);
            jTextField4.setEnabled(true);
            jTextField3.setEnabled(true);
        }
        
        if (numberOfPlayers == 6)
        {
            jTextField6.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField4.setEnabled(true);
            jTextField3.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_onChangeNumber1

    private void printLabel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printLabel
        // TODO add your handling code here:
        lblRetirementInfo.setText(Integer.toString(sldrRetirement.getValue()));
    }//GEN-LAST:event_printLabel

    
    
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkPlayer1;
    private javax.swing.JCheckBox chkPlayer2;
    private javax.swing.JCheckBox chkPlayer3;
    private javax.swing.JCheckBox chkPlayer4;
    private javax.swing.JCheckBox chkPlayer5;
    private javax.swing.JCheckBox chkPlayer6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblRetirementInfo;
    private javax.swing.JSlider sldrRetirement;
    private javax.swing.JSpinner spnNumberOfPlayers;
    // End of variables declaration//GEN-END:variables




}




